name: Python Unit Tests
on:
  push:
    branches: "*"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Ubuntu packages
        run: |
          sudo apt-get -y install build-essential gcc gfortran libblas-dev liblapack-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements-test.txt
      - name: Python unit tests
        run: |
          coverage run --source=mymodule -m unittest
      - name: Test coverage
        run: |
          coverage report > coverage.txt
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.txt
